<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
namespace Unit2\HelloWorldRedirect\Controller\Adminhtml\Action;

class Helloworld extends \Magento\Backend\App\Action
{
    /**
     * Execute method
     */
    public function execute()
    {
        $resultRedirect = $this->resultRedirectFactory->create();
        $resultRedirect->setPath('catalog/category/edit/id/9');
        return $resultRedirect;
    }

    /**
     * Link must be generated by server side
     *
     * @return bool
     */
    public function _processUrlKeys()
    {
        return true;
    }
}
